services:
  - type: web
    name: deu-10th-fukuoka-trip
    env: docker
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 3000
      - key: YPERSISTENCE
        value: /data/yjs-db
    disk:
      name: yjs-data
      mountPath: /data
      sizeGB: 1
